Make 'syntax-changes' file a little more structured Renamed 'syntax-chagnes' file to fit rest of bundle Add l3styleguide and l3syntax-changes to distributed documentation
git-svn-id: http://www.latex-project.org/svnroot/experimental/trunk@2626 de43f980-851b-0410-b2f7-c40aca1f87e0

diff --git a/l3kernel/Makefile b/l3kernel/Makefile
--- a/l3kernel/Makefile
+++ b/l3kernel/Makefile
@@ -66,8 +66,8 @@ TDSDIR   := $(TESTDIR)/tds
 # Data for local installation and TDS construction           #
 ##############################################################
 
-INCLUDEPDF  := expl3 source3
-INCLUDETEX  := interface3 source3 source3body
+INCLUDEPDF  := expl3 l3styleguide l3syntax-changes source3
+INCLUDETEX  := interface3 l3styleguide l3syntax-changes source3 source3body
 INCLUDETXT  := README
 PACKAGEROOT := latex/$(PACKAGE)
 
@@ -199,6 +199,32 @@ $(TESTDIR)/%.pdf: $(TESTDIR)/%.dtx
 ################################################################
 # File building: specials                                      #
 ################################################################
+
+$(TESTDIR)/l3styleguide.pdf: $(TESTDIR)/l3styleguide.tex
+	echo "Typesetting l3styleguide" ; \
+	cd $(TESTDIR) ; \
+	pdflatex -draftmode -interaction=nonstopmode "$(PDFSETTINGS) \input $<" > /dev/null ; \
+	if [ $$? = 0 ] ; then  \
+	  pdflatex -interaction=nonstopmode "$(PDFSETTINGS) \input $<" > /dev/null ; \
+	else \
+	  echo "  Compilation failed" ; \
+	fi ; \
+	for I in $(AUXFILES) ; do \
+	  rm -f l3styleguide.$$I ; \
+	done
+	
+$(TESTDIR)/l3syntax-changes.pdf: $(TESTDIR)/l3syntax-changes.tex
+	echo "Typesetting l3syntax-changes" ; \
+	cd $(TESTDIR) ; \
+	pdflatex -draftmode -interaction=nonstopmode "$(PDFSETTINGS) \input $<" > /dev/null ; \
+	if [ $$? = 0 ] ; then  \
+	  pdflatex -interaction=nonstopmode "$(PDFSETTINGS) \input $<" > /dev/null ; \
+	else \
+	  echo "  Compilation failed" ; \
+	fi ; \
+	for I in $(AUXFILES) ; do \
+	  rm -f l3styleguide.$$I ; \
+	done
 
 $(TESTDIR)/source3.pdf: $(TESTDIR)/source3.tex $(TESTDIR)/source3body.tex $(TESTDIR)/interface3.tex 
 	echo "Typesetting source3" ; \
